# Generated by Django 4.2.4 on 2023-08-20 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comapny",
            new_name="Company",
        ),
    ]
