# Generated by Django 4.2.4 on 2023-08-26 04:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core_api", "0002_rename_comapny_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="area",
        ),
        migrations.RemoveField(
            model_name="company",
            name="city",
        ),
        migrations.RemoveField(
            model_name="company",
            name="country",
        ),
        migrations.RemoveField(
            model_name="company",
            name="district",
        ),
        migrations.RemoveField(
            model_name="company",
            name="dno",
        ),
        migrations.RemoveField(
            model_name="company",
            name="state",
        ),
        migrations.RemoveField(
            model_name="user",
            name="comapny",
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dno", models.CharField(max_length=30)),
                ("area", models.CharField(max_length=30)),
                ("city", models.CharField(max_length=30)),
                ("district", models.CharField(max_length=25)),
                ("state", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=20)),
                (
                    "gst",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "\\d{2}[A-Z]{5}\\d{4}[A-Z]{1}[A-Z\\d]{1}[Z]{1}[A-Z\\d]{1}",
                                message="Enter a Valid Indian GST Number",
                            )
                        ],
                    ),
                ),
                ("mobile", models.CharField(max_length=15)),
                (
                    "phone",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^(?:(?:\\+|0{0,2})91(\\s*[\\ -]\\s*)?|[0]?)?[789]\\d{9}|(\\d[ -]?){10}\\d$",
                                message="Enter a Valid Indian Phone Number",
                            )
                        ],
                    ),
                ),
                ("pan", models.CharField(max_length=15)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_api.company",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core_api.branch",
            ),
        ),
    ]
