# Generated by Django 4.2.4 on 2023-08-26 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_api", "0003_remove_company_area_remove_company_city_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="type",
        ),
    ]
