# Generated by Django 4.2.4 on 2023-08-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_api", "0004_remove_company_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
