# Generated by Django 4.2.4 on 2023-08-26 06:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_api", "0005_branch_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="pan",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        "[A-Z]{5}\\d{4}[A-Z]{1}[A-Z\\d]{1}",
                        message="Enter a Valid PAN Number",
                    )
                ],
            ),
        ),
    ]
