# Generated by Django 4.2.4 on 2023-08-26 06:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_api", "0006_alter_branch_pan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="phone",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        "\\+?\\d[\\d -]{8,12}\\d",
                        message="Enter a Valid Indian Phone Number",
                    )
                ],
            ),
        ),
    ]
