# Generated by Django 4.2.4 on 2023-08-27 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_api", "0008_alter_branch_pan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
    ]
