# Generated by Django 4.2.4 on 2023-09-23 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_api", "0013_purchase_sale_saleorder_saleorderitem_saleitem_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseorder",
            name="invoice_value",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="taxble_value",
        ),
        migrations.RemoveField(
            model_name="saleorder",
            name="invoice_value",
        ),
        migrations.RemoveField(
            model_name="saleorder",
            name="taxble_value",
        ),
    ]
