# Generated by Django 4.2.4 on 2023-11-06 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0014_remove_purchaseorder_invoice_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core_api.branch'),
        ),
    ]
