# Generated by Django 4.2.4 on 2023-11-25 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core_api", "0017_address_address_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="saleorderitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="saleorderitem",
            name="so",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="so",
        ),
        migrations.AddField(
            model_name="sale",
            name="address",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="so_address",
                to="core_api.address",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sale",
            name="branch",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core_api.branch",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sale",
            name="comment",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sale",
            name="gst_type",
            field=models.CharField(
                choices=[("I", "INTER"), ("O", "OUTER"), ("NO", "NOGST")],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sale",
            name="shipping_address",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="so_shipping",
                to="core_api.address",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sale",
            name="vendor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core_api.party",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="SaleOrder",
        ),
        migrations.DeleteModel(
            name="SaleOrderItem",
        ),
    ]
