# Generated by Django 4.2.4 on 2023-11-25 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "core_api",
            "0018_remove_saleorderitem_product_remove_saleorderitem_so_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="sale",
            old_name="vendor",
            new_name="party",
        ),
    ]
