# Generated by Django 4.2.4 on 2023-11-25 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_api", "0019_rename_vendor_sale_party"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="branch",
        ),
    ]
