# Generated by Django 4.2.4 on 2023-11-26 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core_api", "0020_remove_sale_branch"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("ifsc", models.CharField(max_length=11)),
                ("branch", models.CharField(max_length=25)),
                ("address", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="PartyBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("ifsc", models.CharField(max_length=11)),
                ("branch", models.CharField(max_length=25)),
                ("address", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("cheque_no", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "rec_type",
                    models.CharField(
                        choices=[
                            ("BK", "BANK"),
                            ("CQ", "CHEQUE"),
                            ("CA", "CASH"),
                            ("UPI", "UPI"),
                        ],
                        max_length=3,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("date", models.DateTimeField(auto_now=True)),
                (
                    "bank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_api.bank",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core_api.party"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("cheque_no", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "rec_type",
                    models.CharField(
                        choices=[
                            ("BK", "BANK"),
                            ("CQ", "CHEQUE"),
                            ("CA", "CASH"),
                            ("UPI", "UPI"),
                        ],
                        max_length=3,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("date", models.DateTimeField(auto_now=True)),
                (
                    "our_bank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="our_bank",
                        to="core_api.bank",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core_api.party"
                    ),
                ),
                (
                    "party_bank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="party_bank",
                        to="core_api.bank",
                    ),
                ),
            ],
        ),
    ]
