# Generated by Django 4.2.4 on 2023-11-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_api", "0021_bank_partybank_receipt_payment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="rec_type",
            new_name="tran_type",
        ),
        migrations.RenameField(
            model_name="receipt",
            old_name="rec_type",
            new_name="tran_type",
        ),
        migrations.AddField(
            model_name="bank",
            name="account_no",
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="partybank",
            name="account_no",
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
