# Generated by Django 4.2.4 on 2023-12-02 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core_api", "0022_rename_rec_type_payment_tran_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="party_bank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="party_bank",
                to="core_api.partybank",
            ),
        ),
    ]
