# Generated by Django 4.2.4 on 2023-12-03 08:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core_api", "0023_alter_payment_party_bank"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="branch",
        ),
        migrations.AddField(
            model_name="company",
            name="area",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="city",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="country",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="district",
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="dno",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="gst",
            field=models.CharField(
                default=1,
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "\\d{2}[A-Z]{5}\\d{4}[A-Z]{1}[A-Z\\d]{1}[Z]{1}[A-Z\\d]{1}",
                        message="Enter a Valid Indian GST Number",
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="mobile",
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="pan",
            field=models.CharField(
                default=1,
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        "[A-Z]{5}\\d{4}[A-Z]{1}", message="Enter a Valid PAN Number"
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="phone",
            field=models.CharField(
                default=1,
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        "\\+?\\d[\\d -]{8,12}\\d",
                        message="Enter a Valid Indian Phone Number",
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="state",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core_api.company",
            ),
        ),
        migrations.DeleteModel(
            name="Branch",
        ),
    ]
