# Generated by Django 4.2.4 on 2023-12-09 09:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0024_remove_user_branch_company_area_company_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='pan',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('[A-Z]{5}\\d{4}[A-Z]{1}', message='Enter a Valid PAN Number')]),
        ),
        migrations.AlterUniqueTogether(
            name='party',
            unique_together={('name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'user')},
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gst_slab', models.CharField(choices=[(0, 0), (5, 5), (12, 12), (18, 18), (28, 28)], max_length=5)),
                ('hsn', models.CharField(max_length=35)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'user')},
            },
        ),
    ]
