# Generated by Django 4.2.4 on 2023-12-09 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0025_alter_company_pan_alter_party_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='party',
            unique_together={('name', 'user')},
        ),
        migrations.AlterField(
            model_name='party',
            name='gst',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('\\d{2}[A-Z]{5}\\d{4}[A-Z]{1}[A-Z\\d]{1}[Z]{1}[A-Z\\d]{1}', message='Enter a Valid Indian GST Number')]),
        ),
        migrations.AlterUniqueTogether(
            name='party',
            unique_together={('pan', 'user'), ('name', 'user'), ('gst', 'user')},
        ),
    ]
