# Generated by Django 4.2.4 on 2023-12-09 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0026_alter_party_unique_together_alter_party_gst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partybank',
            name='party',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core_api.party'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='bank',
            unique_together={('account_no', 'user'), ('name', 'account_no', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='partybank',
            unique_together={('name', 'account_no', 'party'), ('account_no', 'party')},
        ),
    ]
